name: CI Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ] # Berjalan otomatis saat push ke branch main
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login ke Docker Hub menggunakan Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Setup Docker Buildx (untuk optimasi build)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build dan Push BACKEND
      - name: Build and push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend        # Folder tempat kode backend berada
          file: ./backend/Dockerfile # Lokasi Dockerfile backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/smart-finance-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/smart-finance-backend:${{ github.sha }}

      # 5. Build dan Push FRONTEND
      - name: Build and push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend        # Folder tempat kode frontend berada
          file: ./frontend/Dockerfile # Lokasi Dockerfile frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/smart-finance-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/smart-finance-frontend:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted # Menggunakan runner di PC lokal Anda
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Local Kubernetes
        run: |
          # Melakukan update image dengan tag commit terbaru
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/backend-hpa.yaml
          kubectl apply -f k8s/backend-monitor.yaml
          
          # Force rollout agar pod menggunakan image terbaru
          kubectl rollout restart deployment/backend
          kubectl rollout restart deployment/frontend